### ISSUE TITLE
Display status/diagnostics information

### ISSUE THREAD

**Issue by HvanderGeest** [nuts-foundation/nuts-registry-admin-demo#95]
When developing it could be useful to have access to the diagnostics information displayed in the nutsadmin.

The use case would be when still in development phase and the nutsnode has been blocked off from the outside world, it becomes more difficult to get access to this information(https://nuts-node.readthedocs.io/en/stable/pages/deployment/recommended-deployment.html).

Since the admin demo already communicates with the node internally, it could display this information to have easy access to it.

**Comment by reinkrul** [comment]
Some endpoints of the Nuts Node need to be exposed to the outside world (e.g. HTTP `/n2n`), so there will always be a HTTP proxy in front of it. And then the diagnostics are just another endpoint to expose/secure, alongside others.

I don't think we're going to support this, so closing it for now.
